### PR TITLE
Color list

### PR DESCRIPTION
**Pull request by bettse**
screen shot 2016-11-07 at 4 28 53 pm

### CODE REVIEW

**Comment by bettse** [comment]
@greeze ok, new PR with modified version of the React-Color Block to add labels.  Since the two files I brought it in were a long ways from working with lint, I said fuck it and removed most of the lint.

**Comment by greeze** [comment]
I disapprooooooooove of the lint removal. Maybe disable it temporarily instead? The rules definitely needed some tweaking, but don't throw the baby out with the bathwater, you monster.

I suggest moving the CSS out of the .jsx files and into CSS files, and using `className` attribute instead of `style` attribute on your elements  (as in `app/containers/HomePage/index.js`). It declutters the code and makes it easier to share the CSS later.

The rest looks good! I'd like to get in there and fix the annoying linting rules sometime soon if time permits.

**Comment by adamdicarlo** [comment]
Want me to PR switching this thing to Standard? If you're gonna lint and you get to choose... choose Standard 😁

**Comment by bettse** [comment]
heck yeah

**Comment by adamdicarlo** [comment]
no wait, merge this one :D

**Comment by adamdicarlo** [comment]
okay, about that linting... did the linting ever work in this boilerplate? they're using do expressions (a stage-0 ECMAScript feature) and I don't think there's an eslint plugin for that...

I think porting over to `react-scripts` (via `create-react-app`) or doing the "clean" thing that the existing boilerplate offers would be a good idea.

**Comment by bettse** [comment]
I re-added the linting and fixed the file to pass.  I'll merge this, but I'm open to changing the app to be based on different boilerplate.  I don't think we can use `npm run clean` though, the docs say its self-destructive and can only be run once to set up the project initially(https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/commands.md#cleaning).  I assume I did that when I was setting this up.  Shouldn't be a big issue though, you can make a branch, delete everything, run the commands to generate the new project, and pull over what you need of the old code.

**Pull request merged**
