### PR TITLE
Explain colors

### PR DESCRIPTION
**Pull request by bettse**
An idea for explaining the colors using an interactive bar that changes the descriptive text below.

screen shot 2016-11-04 at 7 18 48 pm
screen shot 2016-11-04 at 7 18 41 pm

### CODE REVIEW

**Comment by bettse** [comment]
@greeze What do you think?  I would prefer tooltips or something, but I'm not quite sure how to do that.

**Comment by greeze** [comment]
👀

**Comment by greeze** [comment]
The color slider would be very useful in cases when the color is known or within a known range, or the user wants a more free-form approach to choosing a color without having to type in hex values. I think it's more useful for creativity than it is for quickly conveying meaning.

It could be useful if you **receive** a blink and want to check its meaning, but not so useful if you intend to **send** a specific message but don't know its associated color.

### Receiving
For the **receive** case, I think a more straightforward approach would be to display the semantic meaning of a color right on the user's card:
team_blink

### Sending
For the **send** case, we could add `title` attributes to our existing swatches (easy):
```html
<div class="swatch" title="Negative" style="background-color: red;"></div>
```
fullscreen_11_5_16__1_36_pm

...or, instead of a grid of swatches, use a dropdown-style component populated with predefined messages and their associated colors (less easy, but arguably cooler):
dropdown___semantic_ui

...or some other approach that treats the intended message as the known and the color as the unknown.

**Comment by greeze** [comment]
Also, I think the slider is very cool and worth keeping around. It might be worth spending some time pulling the logic for associating color values with messages into a shared utility so other components can use it.

**Comment by bettse** [comment]
ooo; awesome feedback.  I really like the tooltip idea for the existing picker style.  I totally see what you mean about the slider making more sense if the input were more free-form

**Comment by adamdicarlo** [comment]
I like the idea of the dropdown a lot. Maybe even more so if it were always expanded.

**Comment by bettse** [comment]
Something like this?

screen shot 2016-11-06 at 8 43 37 pm

**Comment by greeze** [comment]
I like it! If the list gets too long, we might want to make it scrollable. But for now I think it's perfectly wieldy.

**Comment by adamdicarlo** [comment]
Merge?

**Pull request closed without merging**
